---

 - name: Include variables
   include_vars: variables.yml

 - name: STAGE ENV - Launching app server

   environment:
     http_proxy: PROXY_HTTP
     https_proxy: PROXY_HTTPS

   docker:
     name: '{{ STAGE_APP_SERVER }}'
     image: '{{ IMAGE_NAME }}'
     pull: always
     state: started
     tty: yes
     stdin_open: yes
     command: "/bin/bash"
     ports: '{{ STAGE_APP_PORT }}'
     expose: 80

 - name: STAGE ENV - Launching selenuim server for automation testing
   docker:
     image: '{{ IMAGE_NAME }}'
     name: '{{ STAGE_TEST_SERVER }}'
     pull: always
     command: "/bin/bash"
     state: started
     tty: yes
     stdin_open: yes

 - name: STAGE ENV - Transfering web server related config files
   copy: src=scripts/script.sh dest=/var/tmp/script.sh owner=root group=root mode=0777

 - name: STAGE ENV - Transfering test environment related config files
   copy: src=scripts/selenium.sh dest=/var/tmp/selenium.sh owner=root group=root mode=0777

 - name: STAGE ENV - Configuring web app server
   script: docker.sh '{{ STAGE_APP_SERVER }}'

 - name: STAGE ENV - Configuring server for selenium testing
   script: docker_selenium.sh '{{ STAGE_TEST_SERVER }}'
